# This is a basic workflow to help you get started with Actions

name: CD-pipeline-cosmos

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setting up node_modules and angular-cli
        run: |
          echo Initiating angular-cli installation v9.1.3..........
          npm install @angular/cli@9.1.3
          echo Initiating node_modules installation..............
          npm install
          echo Initiating Build............
          npm run build:prod
          echo Build created successfully..................
          cd dist/cosmos
          git config --global user.email "kunwarpadmesh@yahoo.com"
          git config --global user.name "Padmesh"
          git init
          git add .
          git commit -m "build commit"
          echo Build directory initiated with git successfully............

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}


      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
